# Generated by Django 3.1.7 on 2021-03-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocios',
            name='cache',
        ),
    ]
